name: deploy

on: #trigger on push & PR to this branch only
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

env:
  JAVA_VERSION: "12.x" #change this version if you want
  FLUTTER_CHANNEL: "stable" #set here your channel

jobs:
  flutter_test:
    name: Analyze
    runs-on: ubuntu-latest #change it to another OS if you want
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
      - run: |
          flutter clean 
          flutter pub get 
          flutter analyze 
          flutter format lib/
  # build_web:
  #   name: Build for WEB
  #   needs: [flutter_test] #only trigger this, if the flutter_test job runs ok...
  #   runs-on: ubuntu-latest #change it to another OS if you want
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: ${{env.FLUTTER_CHANNEL}}
  #     - run: |
  #         flutter pub get
  #         flutter build web
  publish_Github_Pages:
    name: Publish GH Pages
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}
    runs-on: ubuntu-latest #change it to another OS if you want
    steps:
      - name: Get current date
        id: date
        run: echo "DATE_ENV=$(date +'%d-%m-%Y')" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /web/
      # - run: |
      #     flutter pub get
      #     flutter build web --release
      #     cd build/web
      #     git init
      #     git config --global user.email gabeaventh@gmail.com
      #     git config --global user.name gabeaventh
      #     git status
      #     git remote add origin https://${{ secrets.ACCESS_TOKEN }}@github.com/gabeaventh/my-jsonapi.git #change to your path
      #     git checkout -b gh-pages
      #     git add --all
      #     git commit -m "Deploy ${{ steps.date.outputs.date }}"
      #     git push origin gh-pages -f